# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Eos"
license = "MIT"
licenselink = "https://mit-license.org/"
description = ""
homepage = ""
tags = ["", ""]
features = ["", ""]
min_version = 0.18

[author]
  name = "Joshua Seigler"
  homepage = "https://joshua.seigler.net/"

# Original theme from scratch
