languageCode = "en-us"
title = "joshua.seigler.net"
baseurl = "https://seigler.github.io/joshua.seigler.net/"
source = "src/"
publishDir = "../dist"
theme = "eos"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = -1
