languageCode = "en-us"
title = "joshua.seigler.net"
baseurl = "https://joshua.seigler.net/"
source = "src/"
publishDir = "../dist"
theme = "eos"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = -1
[[menu.main]]
  name = "Posts"
  url = "/posts"
